# Pandas Giriş

Pandas veri bilimi dünyasında ismini en çok duyduğumuz kütüphanelerden biridir. Özellikle bu işlerde henüz yeniyseniz aşağıda paylaşılan linke bakmanızda oldukça büyük yarar var.

https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html

Pandas kütüphanesinin çok kullanışlı bir çok özelliği bulunur. İşte bunlardan bazıları;

- Sayısal ve sayısal olmayan verilerinde **eksik verilerin** (NaN olarak temsil edilir) kolay bir şekilde işlenmesi. 
- DataFrame objelerden sütunlar **eklenebilmesi ve silinebilmesi**. 
- Veri kümelerini toplayarak ve dönüştürerek üzerinde bölme-uygulama-birleştirme işlemleri gerçekleştirmek için verileri **gruplaması**. 
- Diğer Python ve NumPy veri yapılarındaki düzensiz, farklı şekillerde indexlenmiş verileri DataFrame nesnelerine **dönüştürmeyi kolaylaştırması**.
- Akıllı **etiket tabanlı bölümlendirme**, **indeksleme** ve büyük veri kümelerinin **subsetlenmesi**. 
- Veri kümelerinin **birleştirebilmesi**. 
- Excel dosyalarından, veritabanlarından veri yüklemek ve ultra hızlı HDF5 formatından veri kaydetmek/yüklemek için **güçlü IO araçları** olması.

## Pandas Versiyon Kontrolü & Ön Tanımlı Parametreler

In [1]:
# 'Pandas' kütüphanesini 'pd' kısaltmasını kullanacak şekilde import ediyoruz (literatürde kullanılan kısaltma)
import pandas as pd
import numpy as np

In [2]:
# Eğer bir hatayla karşılaşıyorsanız, versiyon kontrolü yapmak yardımcı olabilir
print("Pandas version:", pd.__version__)
print("Numpy version:", np.__version__)

Pandas version: 1.2.4
Numpy version: 1.20.2

In [3]:
# Pandas'a özel parametreler
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 25)
pd.set_option('display.precision', 3)

## Veri Yapıları

### 1. Series

Series objeleri aslında "**Tek boyutlu array**" yapılarıdır. Bunların önemli bir yönü, bir "indeks" değeri taşımalarıdır.

In [4]:
pd.Series # Series veri yapısıyla ilgili dökümantasyon (SHİFT + TAB)

pandas.core.series.Series

In [5]:
# Series Objesi Oluşturma
s = pd.Series([1, 3, 5, np.nan, 6, 8])

s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

### 2. DataFrame

DataFrame objeleri aslında bir çoğumuzun Excel gibi araçlar aşina olduğu "**sütun ve satırlardan oluşan tablo**" yapılarıdır. Bu kavram, veriler üzerinde yapacağımız analizlerin temelini oluşturur. Yapısal olarak, bir DataFrame, aynı indekse sahip bir dizi nesnenin bir birleşimi olarak düşünülebilir.

In [6]:
pd.DataFrame # DataFrame veri yapısıyla ilgili dökümantasyon (SHİFT + TAB)

pandas.core.frame.DataFrame

In [7]:
# NumPy kütüphanesini kullanarak DataFrame tanımlama
df1 = pd.DataFrame(np.random.randn(6, 4), columns=list('ABCD'))
df1

       A      B      C      D
0 -0.810  1.671  0.467 -1.290
1 -0.328 -1.005 -0.488 -1.692
2  0.738 -0.110 -0.444  0.564
3  0.016  0.279  1.171 -0.306
4  0.935  1.027  1.666 -0.691
5  0.373 -0.848 -1.609 -0.749

In [8]:
# Dictionary(sözlük) veri tipini kullanarak DataFrame tanımlama
df2 = pd.DataFrame({
    'A': 1.,
    'B': pd.Timestamp('20130102'),
    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
    'D': np.array([3] * 4, dtype='int32'),
    'E': pd.Categorical(["test", "train", "test", "train"]),
    'F': 'foo'
})
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

## Veri Seti Yükleme

Pandas'a veri seti yüklemenin bir çok yolu vardır. Çalışmalarınızda kullanacağınız veri setlerini bulmak için bazı güzel kaynaklar;

- http://archive.ics.uci.edu/ml/index.php
- https://datasetsearch.research.google.com/
- https://opendata.cityofnewyork.us/
- https://data.world/
- https://www.kaggle.com/datasets
- Ve çok daha fazlası...

### "Census Income" Veri Seti

Pandas kütüphanesi bilgisayarımızda hali hazırda var olan `xlsx`, `txt`, `csv`, `json`, `sql` gibi formatlardaki verileri doğrudan okuyabildiği gibi internet aracılığıyla erişebildiğimiz veri setlerini de okumamıza olanak sağlar.

In [9]:
# Veriye internet üzerinden istediğim sütun isimlerine göre ulaşma
columns = [
    'age', 'workclass', 'fnlwgt', 'education', 'education_num',
    'marital_status', 'occupation', 'relationship', 'ethnicity', 'gender',
    'capital_gain', 'capital_loss', 'hours_per_week', 'country_of_origin',
    'income'
]

df = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data', names=columns)

> Veriyi incelemeye başlamadan önce ilk olarak metadatasına bakmak da her zaman yarar var.
> https://archive.ics.uci.edu/ml/datasets/census+income

## Verinin İçeriğini Görüntüleme

* .info() 
* .head()
* .tail()
* .sample()
* .columns
* .dtypes
* .rename()

### Info

DataFrame içerisinde yer alan sütunlar, bu sütunların veri tipleri, toplam kaç adet kayıt olduğu, boş değer olup olmadığı, hafızada kapladığı alan gibi, veri setimiz hakkında genel anlamda bilgi sahibi olmamızı sağlar.

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                32561 non-null  int64
 1   workclass          32561 non-null  object
 2   fnlwgt             32561 non-null  int64
 3   education          32561 non-null  object
 4   education_num      32561 non-null  int64
 5   marital_status     32561 non-null  object
 6   occupation         32561 non-null  object
 7   relationship       32561 non-null  object
 8   ethnicity          32561 non-null  object
 9   gender             32561 non-null  object
 10  capital_gain       32561 non-null  int64
 11  capital_loss       32561 non-null  int64
 12  hours_per_week     32561 non-null  int64
 13  country_of_origin  32561 non-null  object
 14  income             32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

### Head

DataFrame içerisinden **baştan** başlayacak şekilde istediğimiz sayıda kayıt getirir.

In [11]:
df.head(10)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,ethnicity,gender,capital_gain,capital_loss,hours_per_week,country_of_origin,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K

### Tail

DataFrame içerisinden **sondan** başlayacak şekilde istediğimiz sayıda kayıt getirir.

In [12]:
df.tail()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,ethnicity,gender,capital_gain,capital_loss,hours_per_week,country_of_origin,income
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

### Sample

DataFrame içerisinden **rastgele** bir şekilde istediğimiz sayıda kayıt getirir.

In [13]:
df.sample(8)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,ethnicity,gender,capital_gain,capital_loss,hours_per_week,country_of_origin,income
13801,39,Self-emp-not-inc,103110,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K
6045,52,Self-emp-not-inc,313243,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,55,United-States,>50K
12035,65,Self-emp-not-inc,22907,7th-8th,4,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,40,United-States,<=50K
6203,50,Private,182360,HS-grad,9,Separated,Prof-specialty,Unmarried,Other,Female,0,0,60,Puerto-Rico,<=50K
1493,53,State-gov,156877,HS-grad,9,Married-civ-spouse,Adm-clerical,Husband,White,Male,15024,0,35,United-States,>50K
26912,32,Self-emp-inc,103078,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,40,United-States,<=50K
12067,55,Private,124137,HS-grad,9,Married-spouse-absent,Machine-op-inspct,Not-in-family,White,Male,0,0,40,Poland,<=50K
12989,22,Private,207782,Assoc-acdm,12,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,20,United-States,<=50K

> **SORU:** Eğer bu kod satırını tekrardan çalıştırırsam ne olur?

```python
df.sample(8, random_state=42) # Ne işe yarıyor bu random state?
```

### Columns

DataFrame içerisindeki **sütunların adlarını** döndürür.

In [14]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'ethnicity', 'gender',
       'capital_gain', 'capital_loss', 'hours_per_week', 'country_of_origin',
       'income'],
      dtype='object')

### Dtypes

DataFrame içerisindeki her bir **sütunun veri tiplerini** döndürür.

In [15]:
df.dtypes

age                   int64
workclass            object
fnlwgt                int64
education            object
education_num         int64
marital_status       object
occupation           object
relationship         object
ethnicity            object
gender               object
capital_gain          int64
capital_loss          int64
hours_per_week        int64
country_of_origin    object
income               object
dtype: object

### Rename Columns

DataFrame içerisinde var olan bir **sütunun ismini değiştirmek** istediğimizde kullanırız.

In [16]:
df.rename(columns={'country_of_origin': 'native_country'}, inplace=True)
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,ethnicity,gender,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

> **SORU:** `inplace=True` parametresini tanımlamaya neden ihtiyaç duydum, kullanmasam ne olurdu?

## Veri Setine İstatistiksel Değerler

* .describe()
* .value_counts()
* .mean()
* .std()
* .min()
* .max()
* .unique()

### Describe

DataFrame içerisinde yer alan sayısal sütunlara ait **temel istatiksel değerleri** döndürür.

In [17]:
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000,3.256e+04,32561.000,32561.000,32561.000,32561.000
mean,38.582,1.898e+05,10.081,1077.649,87.304,40.437
std,13.640,1.055e+05,2.573,7385.292,402.960,12.347
min,17.000,1.228e+04,1.000,0.000,0.000,1.000
25%,28.000,1.178e+05,9.000,0.000,0.000,40.000
50%,37.000,1.784e+05,10.000,0.000,0.000,40.000
75%,48.000,2.371e+05,12.000,0.000,0.000,45.000
max,90.000,1.485e+06,16.000,99999.000,4356.000,99.000

### Value_Counts()

DataFrame içerisinde belirttiğimiz sütunda yer alan değerlerden **hangisinden kaç tane** olduğunu döndürür.

In [18]:
df['education']

0          Bachelors
1          Bachelors
2            HS-grad
3               11th
4          Bachelors
            ...
32556     Assoc-acdm
32557        HS-grad
32558        HS-grad
32559        HS-grad
32560        HS-grad
Name: education, Length: 32561, dtype: object

In [19]:
type(df.education)

pandas.core.series.Series

In [20]:
df.education.value_counts()

 HS-grad         10501
 Some-college     7291
 Bachelors        5355
 Masters          1723
 Assoc-voc        1382
 11th             1175
 Assoc-acdm       1067
 10th              933
 7th-8th           646
 Prof-school       576
 9th               514
 12th              433
 Doctorate         413
 5th-6th           333
 1st-4th           168
 Preschool          51
Name: education, dtype: int64

```python
df['education'].value_counts() # Aynı çıktıya kodu bu şekilde yazarak da ulaşabiliriz.
```

### Mean() / Std() / Min() / Max() ...

In [21]:
print('Aritmetik Ortalama:', df['hours_per_week'].mean())
print('Standart Sapma:', df['hours_per_week'].std())
print('Minimum:', df['hours_per_week'].min())
print('Maximum:', df['hours_per_week'].max())

Aritmetik Ortalama: 40.437455852092995
Standart Sapma: 12.347428681731843
Minimum: 1
Maximum: 99

### Unique()

DataFrame içerisinde belirttiğimiz sütundaki sadece **benzersiz (eşsiz)** değerleri döndürür.

In [22]:
df.education.unique()

array([' Bachelors', ' HS-grad', ' 11th', ' Masters', ' 9th',
       ' Some-college', ' Assoc-acdm', ' Assoc-voc', ' 7th-8th',
       ' Doctorate', ' Prof-school', ' 5th-6th', ' 10th', ' 1st-4th',
       ' Preschool', ' 12th'], dtype=object)

> **SORU:** Gözümüze çarpan tuhaf bir durum var mı?

In [23]:
df["education"] = df.education.str.strip()

In [24]:
df.education.unique() # Şimdi oldu :)

array(['Bachelors', 'HS-grad', '11th', 'Masters', '9th', 'Some-college',
       'Assoc-acdm', 'Assoc-voc', '7th-8th', 'Doctorate', 'Prof-school',
       '5th-6th', '10th', '1st-4th', 'Preschool', '12th'], dtype=object)

## Satırları ve Sütunları Seçme

Burada kullanacağımız 2 temel yaklaşımımız bulunmakta,

### .loc 

* Satırları ve sütunları ismine göre seçer
* **Sütun ismine göre**             `.loc[]`

### .iloc

* Satırları ve sütunları index numarasına göre seçer
* **İndex numarasına göre**  `.iloc[]`

In [25]:
# İndex numarasına göre satır seçme
df.iloc[3]

age                                53
workclass                     Private
fnlwgt                         234721
education                        11th
education_num                       7
marital_status     Married-civ-spouse
occupation          Handlers-cleaners
relationship                  Husband
ethnicity                       Black
gender                           Male
capital_gain                        0
capital_loss                        0
hours_per_week                     40
native_country          United-States
income                          <=50K
Name: 3, dtype: object

In [26]:
# Şimdi ilk 3 satır karşımıza çıktı, aynı Python'daki index yapıları gibi :)
df.iloc[0:3]

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,ethnicity,gender,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K

In [27]:
# Belirli bir satır aralığını seçme
df.iloc[10:15]

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,ethnicity,gender,capital_gain,capital_loss,hours_per_week,native_country,income
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K

In [28]:
# Peki son 2 satır? Bu da aynıymış :)
df.iloc[-2:]

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,ethnicity,gender,capital_gain,capital_loss,hours_per_week,native_country,income
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [29]:
# 2'şer satır atlayarak tüm satırları seç ancak aynı zamanda sadece 3. ve 5. sütun arasını görmek istiyorum
df.iloc[::2, 2:5].head()

   fnlwgt  education  education_num
0   77516  Bachelors             13
2  215646    HS-grad              9
4  338409  Bachelors             13
6  160187        9th              5
8   45781    Masters             14

In [30]:
# .loc yapısını kullanarak satır seçme
df.loc[0:3]

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,ethnicity,gender,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K

> **SORU:** Neden 3 satır yerine 4 satırlık bir çıktı verdi, son satır dahil edilmiyordu diye hatırlıyorum?

İşte `.iloc[]` ve `.loc[]` arasındaki fark!

In [31]:
df.loc[0:2, "age":"workclass"]

   age          workclass
0   39          State-gov
1   50   Self-emp-not-inc
2   38            Private

In [32]:
df.iloc[0:3, :2]

   age          workclass
0   39          State-gov
1   50   Self-emp-not-inc
2   38            Private

## Filtreleme İşlemleri

In [33]:
df.age > 50

0        False
1        False
2        False
3         True
4        False
         ...
32556    False
32557    False
32558     True
32559    False
32560     True
Name: age, Length: 32561, dtype: bool

In [34]:
df[df.age > 50].head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,ethnicity,gender,capital_gain,capital_loss,hours_per_week,native_country,income
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K

In [35]:
# Filtreleme işleminden sonra sadece seçtiğim sütunları getir
df.loc[df.age > 50, ['age', 'education', 'occupation', 'gender', 'income']]

       age    education          occupation   gender  income
3       53         11th   Handlers-cleaners     Male   <=50K
7       52      HS-grad     Exec-managerial     Male    >50K
21      54      HS-grad       Other-service   Female   <=50K
24      59      HS-grad        Tech-support   Female   <=50K
25      56    Bachelors        Tech-support     Male    >50K
...    ...          ...                 ...      ...     ...
32542   72      HS-grad                   ?     Male   <=50K
32548   65  Prof-school      Prof-specialty     Male   <=50K
32554   53      Masters     Exec-managerial     Male    >50K
32558   58      HS-grad        Adm-clerical   Female   <=50K
32560   52      HS-grad     Exec-managerial   Female    >50K

[6460 rows x 5 columns]

> **SORU:** Peki aynı filtreleme işlemini `.loc` yerine `.iloc`'la yapmaya çalışsam ne yapmam lazım?

#### Hadi **"GENDER"** sütununu da filtrelemeye çalışalım...

In [36]:
df.gender == 'Male'

0        False
1        False
2        False
3        False
4        False
         ...
32556    False
32557    False
32558    False
32559    False
32560    False
Name: gender, Length: 32561, dtype: bool

> **SORU:** Neden filtreleme sonucu hepsi `False` döndü, veri setimde erkek kişiler de bulunuyordu?

In [37]:
gender_list = []
for gender in df.gender[:10]:
    gender_list.append(gender)
print(gender_list)

[' Male', ' Male', ' Male', ' Male', ' Female', ' Female', ' Female', ' Male', ' Female', ' Male']

In [38]:
df.loc[df.gender == ' Male']

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,ethnicity,gender,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [39]:
# Veri seti içerisinde bulunan boşlukları kaldırma
df.gender = df.gender.apply(lambda x: x.strip())

In [40]:
df.gender == 'Male'

0         True
1         True
2         True
3         True
4        False
         ...
32556    False
32557     True
32558    False
32559     True
32560    False
Name: gender, Length: 32561, dtype: bool

In [41]:
df.loc[df.gender == 'Male']

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,ethnicity,gender,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

#### Şimdi de hem cinsiyeti erkek olanları hem de yaşı 30 ile 40 arasında olanları filtrelemeye çalışalım...

In [42]:
(df.gender == 'Male') & (df.age >= 30) & (df.age <= 40)

0         True
1        False
2         True
3        False
4        False
         ...
32556    False
32557     True
32558    False
32559    False
32560    False
Length: 32561, dtype: bool

In [43]:
df.loc[(df.age >= 30) & (df.gender == 'Male') & (df.age <= 40), :]

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,ethnicity,gender,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32537,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32551,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K

## Boş (NaN) Değerleri Bulma

Aslında `df.info` fonksiyonu ile veri setimizde herhangi bir boş değer olmadığını görmüştük. Ancak yine de tekrardan kontrol edelim.

In [44]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
ethnicity         0
gender            0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

## NaN Değerleri Silme

Öncelikle içerisinde boş değerler barındıran bir `DataFrame` oluşturalım.

In [45]:
null_df = pd.DataFrame([1, 2, 4, np.nan], columns=['column1'])
null_df

   column1
0      1.0
1      2.0
2      4.0
3      NaN

In [46]:
null_df.dropna()

   column1
0      1.0
1      2.0
2      4.0

In [47]:
null_df.isnull()

   column1
0    False
1    False
2    False
3     True

In [48]:
null_df.notnull()

   column1
0     True
1     True
2     True
3    False

## NaN Değerleri Doldurma

In [49]:
null_df = pd.DataFrame([1, 2, 4, np.nan], columns=['column1'])

In [50]:
null_df

   column1
0      1.0
1      2.0
2      4.0
3      NaN

In [51]:
null_df.column1.fillna(1000)

0       1.0
1       2.0
2       4.0
3    1000.0
Name: column1, dtype: float64

In [52]:
null_df

   column1
0      1.0
1      2.0
2      4.0
3      NaN

> **SORU:** Aslında NaN değerin **1000** sayısıyla doldurulduğu gördük ancak neden DataFrame'de hala NaN değer var?

In [53]:
null_df.fillna('random_string')

         column1
0            1.0
1            2.0
2            4.0
3  random_string

NaN değerleri istediğimiz değerle doldurabildiğimiz gibi **istatistiksel yöntemlerden** yararlanarak da bu işlemi gerçekleştirebiliriz.

In [54]:
null_df.fillna(null_df.column1.median())
null_df

   column1
0      1.0
1      2.0
2      4.0
3      NaN

In [55]:
null_df.fillna(null_df.column1.mean(), inplace=True)
null_df

   column1
0    1.000
1    2.000
2    4.000
3    2.333

Aritmetik ortalama, mod, medyan gibi büyüklüklerle boş değerlerimizi doldurabileceğimizi görmüş olduk. Bu yaklaşım, genellikle NaN değerleri kendi belirlediğimiz bir değerle doldurmaktan daha mantıklı sonuçlar verir.

- **Ancak her zaman değil!**

Bu konuyu ilerleyen derslerimizde daha da detaylandıracağız. Ancak şimdilik burada kalalım.

## Group By

Elimizdeki verilerden anlamlı bilgiler elde etmek için onları amacımıza uygun bir şekilde **gruplamak** gerekir. Bu işlemlerin `pandas` üzerinde nasıl yapıldığını inceleyelim.

In [56]:
# Biz bu tarz çıktıları elde etmek için value_counts() fonksiyonundan yararlanıyorduk
df.groupby('relationship').count()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,ethnicity,gender,capital_gain,capital_loss,hours_per_week,native_country,income
relationship,,,,,,,,,,,,,,
Husband,13193,13193,13193,13193,13193,13193,13193,13193,13193,13193,13193,13193,13193,13193
Not-in-family,8305,8305,8305,8305,8305,8305,8305,8305,8305,8305,8305,8305,8305,8305
Other-relative,981,981,981,981,981,981,981,981,981,981,981,981,981,981
Own-child,5068,5068,5068,5068,5068,5068,5068,5068,5068,5068,5068,5068,5068,5068
Unmarried,3446,3446,3446,3446,3446,3446,3446,3446,3446,3446,3446,3446,3446,3446
Wife,1568,1568,1568,1568,1568,1568,1568,1568,1568,1568,1568,1568,1568,1568

In [57]:
df.groupby(['education']).mean()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
education,,,,,,
10th,37.430,196832.465,6.0,404.574,56.846,37.053
11th,32.356,194928.077,7.0,215.098,50.079,33.926
12th,32.000,199097.508,8.0,284.088,32.337,35.781
1st-4th,46.143,239303.000,2.0,125.875,48.327,38.256
5th-6th,42.886,232448.333,3.0,176.021,68.252,38.898
7th-8th,48.446,188079.172,4.0,233.940,65.669,39.367
9th,41.060,202485.066,5.0,342.089,28.998,38.045
Assoc-acdm,37.381,193424.094,12.0,640.399,93.419,40.504
Assoc-voc,38.554,181936.017,11.0,715.051,72.755,41.611
Bachelors,38.905,188055.915,13.0,1756.300,118.350,42.614
Doctorate,47.702,186698.760,16.0,4770.145,262.845,46.973
HS-grad,38.974,189538.740,9.0,576.800,70.467,40.575
Masters,44.050,179852.363,14.0,2562.564,166.720,43.836
Preschool,42.765,235889.373,1.0,898.392,66.490,36.647
Prof-school,44.747,185663.707,15.0,10414.417,231.203,47.425
Some-college,35.756,188742.922,10.0,598.824,71.637,38.852

**ÖNEMLİ NOT:** `groupby` içerisine yazdığımız sütunların sıralaması önemlidir, bu sıralama yapılacak grupların sıralamasını belirler!

In [58]:
df.groupby(['education', 'age'])[['hours_per_week', 'capital_gain']].mean()

                  hours_per_week  capital_gain
education    age
10th         17           21.543       266.659
             18           27.895         0.000
             19           34.500         0.000
             20           39.400         0.000
             21           39.000       229.882
...                          ...           ...
Some-college 81           13.000         0.000
             82           11.500         0.000
             84           35.000         0.000
             88           40.000         0.000
             90           32.833         0.000

[965 rows x 2 columns]

In [59]:
df.groupby(['income', 'native_country']).age.agg(['count', 'mean'])

                         count    mean
income native_country
 <=50K  ?                  437  36.854
        Cambodia            12  35.667
        Canada              82  41.012
        China               55  41.800
        Columbia            57  39.228
...                        ...     ...
 >50K   Thailand             3  32.667
        Trinadad&Tobago      2  42.500
        United-States     7171  44.297
        Vietnam              5  35.400
        Yugoslavia           6  40.167

[82 rows x 2 columns]

`.agg` fonksiyonunu ekranda nasıl çıktılar görmek istiyorsak o şekilde modifiye etme şansına da sahibibiz :)

In [60]:
gb = df.groupby(['income', 'native_country'])
gb_aggs = gb.agg({'age': 'mean', 'capital_gain': 'sum'})
gb_aggs.sample(1)

                          age  capital_gain
income native_country
 <=50K  Ireland        34.579          7787

Eğer veri setinin tümüne ihtiyacımız yoksa, kendi belirlediğimiz bir grup veri içerisinde de gruplama yapabiliriz.

In [61]:
df[df.native_country == ' United-States'].groupby(['education']).hours_per_week.mean()

education
10th            36.915
11th            33.682
12th            34.951
1st-4th         32.913
5th-6th         36.979
7th-8th         39.060
9th             38.035
Assoc-acdm      40.657
Assoc-voc       41.633
Bachelors       42.709
Doctorate       47.409
HS-grad         40.596
Masters         44.169
Preschool       28.118
Prof-school     47.484
Some-college    38.862
Name: hours_per_week, dtype: float64

## Sıralama İşlemleri

`sort_index()` index numaralarına göre sıralama yapmamızı sağlarken, `sort_values()` elde edilen değerlere göre sıralama yapmamıza olanak tanır.

In [62]:
df_grouped = df.groupby(['income', 'native_country']).mean().sort_values('age', ascending=True)
df_grouped

                               age      fnlwgt  education_num  capital_gain  \
income native_country
 <=50K  Taiwan              29.323  181981.290         12.548        71.032
 >50K   Dominican-Republic  30.500  220226.000          9.000     49999.500
        Hong                31.500  294478.833         13.833         0.000
 <=50K  Holand-Netherlands  32.000   27882.000         10.000         0.000
        Guatemala           32.262  266016.016          5.951       116.148
...                            ...         ...            ...           ...
 >50K   Italy               50.360  185383.360         10.960      1253.040
        Poland              50.583  179314.167         11.083      2743.083
        Scotland            52.667  208306.667         10.667      1726.000
        Columbia            53.500  283410.500         15.500         0.000
        Hungary             57.333  172137.333         11.000      1726.000

                            capital_loss  hours_per_week
income native_country
 <=50K  Taiwan                    51.677          33.774
 >50K   Dominican-Republic         0.000          47.000
        Hong                     329.500          45.000
 <=50K  Holand-Netherlands      2205.000          40.000
        Guatemala                 26.131          39.361
...                                  ...             ...
 >50K   Italy                     79.080          45.400
        Poland                     0.000          39.000
        Scotland                   0.000          46.667
        Columbia                   0.000          50.000
        Hungary                    0.000          50.000

[82 rows x 6 columns]

> **SORU:** `ascending=True` parametresini tanımlamamız sıralamada nasıl bir değişikliğe sebep oldu?

In [63]:
df_grouped2 = df.groupby(['income', 'native_country']).mean().sort_values('age')
df_grouped2

                               age      fnlwgt  education_num  capital_gain  \
income native_country
 <=50K  Taiwan              29.323  181981.290         12.548        71.032
 >50K   Dominican-Republic  30.500  220226.000          9.000     49999.500
        Hong                31.500  294478.833         13.833         0.000
 <=50K  Holand-Netherlands  32.000   27882.000         10.000         0.000
        Guatemala           32.262  266016.016          5.951       116.148
...                            ...         ...            ...           ...
 >50K   Italy               50.360  185383.360         10.960      1253.040
        Poland              50.583  179314.167         11.083      2743.083
        Scotland            52.667  208306.667         10.667      1726.000
        Columbia            53.500  283410.500         15.500         0.000
        Hungary             57.333  172137.333         11.000      1726.000

                            capital_loss  hours_per_week
income native_country
 <=50K  Taiwan                    51.677          33.774
 >50K   Dominican-Republic         0.000          47.000
        Hong                     329.500          45.000
 <=50K  Holand-Netherlands      2205.000          40.000
        Guatemala                 26.131          39.361
...                                  ...             ...
 >50K   Italy                     79.080          45.400
        Poland                     0.000          39.000
        Scotland                   0.000          46.667
        Columbia                   0.000          50.000
        Hungary                    0.000          50.000

[82 rows x 6 columns]

- Bu da bize aynı çıktıyı vermiş gibi duruyor, nerede hata yapıyorum???

In [64]:
df_grouped3 = df.groupby(['income', 'native_country']).mean().sort_values('age', ascending=False)
df_grouped3

                               age      fnlwgt  education_num  capital_gain  \
income native_country
 >50K   Hungary             57.333  172137.333         11.000      1726.000
        Columbia            53.500  283410.500         15.500         0.000
        Scotland            52.667  208306.667         10.667      1726.000
        Poland              50.583  179314.167         11.083      2743.083
        Italy               50.360  185383.360         10.960      1253.040
...                            ...         ...            ...           ...
 <=50K  Guatemala           32.262  266016.016          5.951       116.148
        Holand-Netherlands  32.000   27882.000         10.000         0.000
 >50K   Hong                31.500  294478.833         13.833         0.000
        Dominican-Republic  30.500  220226.000          9.000     49999.500
 <=50K  Taiwan              29.323  181981.290         12.548        71.032

                            capital_loss  hours_per_week
income native_country
 >50K   Hungary                    0.000          50.000
        Columbia                   0.000          50.000
        Scotland                   0.000          46.667
        Poland                     0.000          39.000
        Italy                     79.080          45.400
...                                  ...             ...
 <=50K  Guatemala                 26.131          39.361
        Holand-Netherlands      2205.000          40.000
 >50K   Hong                     329.500          45.000
        Dominican-Republic         0.000          47.000
 <=50K  Taiwan                    51.677          33.774

[82 rows x 6 columns]

In [65]:
df.groupby(['income','native_country']).mean().sort_values(['income','age'], ascending=[True,False])

                               age      fnlwgt  education_num  capital_gain  \
income native_country
 <=50K  Cuba                47.286  243906.229          9.043       136.986
        Hungary             47.000  182993.800         10.700       413.800
        Greece              44.667  151661.286          9.190       347.762
        Italy               44.375  179759.375          7.750       277.375
        China               41.800  175689.182         10.309       103.891
...                            ...         ...            ...           ...
 >50K   Nicaragua           34.000  399953.500          9.500         0.000
        Peru                33.500  314562.500         11.500         0.000
        Thailand            32.667  199784.000         12.667         0.000
        Hong                31.500  294478.833         13.833         0.000
        Dominican-Republic  30.500  220226.000          9.000     49999.500

                            capital_loss  hours_per_week
income native_country
 <=50K  Cuba                      19.714          37.986
        Hungary                  166.800          31.300
        Greece                   202.429          41.810
        Italy                      0.000          39.625
        China                     94.418          37.382
...                                  ...             ...
 >50K   Nicaragua                924.000          37.500
        Peru                     924.000          40.000
        Thailand                   0.000          58.333
        Hong                     329.500          45.000
        Dominican-Republic         0.000          47.000

[82 rows x 6 columns]

Her bir `native_country` özelinde, yanında `income` değerlerini de görmek tabloyu okumayı kolaylaştırır gibi duruyor. Peki bunu nasıl yapabiliriz?

In [66]:
df_grouped4 = df.groupby(['income','native_country']).mean().reset_index().sort_values(['income','age'], ascending=[True,False])
df_grouped4

,income,native_country,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
5,<=50K,Cuba,47.286,243906.229,9.043,136.986,19.714,37.986
18,<=50K,Hungary,47.000,182993.800,10.700,413.800,166.800,31.300
12,<=50K,Greece,44.667,151661.286,9.190,347.762,202.429,41.810
22,<=50K,Italy,44.375,179759.375,7.750,277.375,0.000,39.625
3,<=50K,China,41.800,175689.182,10.309,103.891,94.418,37.382
...,...,...,...,...,...,...,...,...
68,>50K,Nicaragua,34.000,399953.500,9.500,0.000,924.000,37.500
69,>50K,Peru,33.500,314562.500,11.500,0.000,924.000,40.000
77,>50K,Thailand,32.667,199784.000,12.667,0.000,0.000,58.333
58,>50K,Hong,31.500,294478.833,13.833,0.000,329.500,45.000
48,>50K,Dominican-Republic,30.500,220226.000,9.000,49999.500,0.000,47.000

`reset_index()` fonksiyonu ile yaptığım gruplama sonucunda elde ettiğim tablodan kendime yeni bir `DataFrame` oluşturmuş oldum. Süper! Artık elde ettiğim bu çıktıyı istediğim her yerde kullanabilirim :)