# Pandas Revize

Ön çalışmada öğrendiklerinizi temel alan bu çalışma şunları yenilememize ve üzerine ekleme yapmamıza yardımcı olacaktır: 
- Pandas DataFrame'ine veri yükleme
- Veriyi keşfetme (`.mean()`, `.value_counts()` vb.)
- Veriyi maskeleme yöntemini kullanarak filtreleme
- Boş değerlerle baş etme (`.dropna()`, `.fillna()`)
- Veriye çeşitli fonksiyonlar uygulama (`.apply()`, `.map()`)
- Veriyi gruplama ve matematiksel işlemlere tabi tutma

## Veri Yükleme

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://bit.ly/2JRmGC2')

Kullanacağımız veri setini Jupyter Notebook'a yükledikten sonra verinin içeriğini keşfetmeye başlamak için `.head()` ve `.info()` fonksiyonlarından yararlanmak bizim için her zaman güzel bir başlangıçtır.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      77 non-null     object
 1   mfr       77 non-null     object
 2   type      77 non-null     object
 3   calories  77 non-null     int64
 4   protein   77 non-null     int64
 5   fat       77 non-null     int64
 6   sodium    77 non-null     int64
 7   fiber     77 non-null     float64
 8   carbo     77 non-null     float64
 9   sugars    77 non-null     int64
 10  potass    77 non-null     int64
 11  vitamins  77 non-null     int64
 12  shelf     77 non-null     int64
 13  weight    77 non-null     float64
 14  cups      77 non-null     float64
 15  rating    77 non-null     float64
dtypes: float64(5), int64(8), object(3)
memory usage: 9.8+ KB

In [4]:
df.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843

`.info()` fonksiyonunu incelediğimizde veri setimiz içerisinde herhangi bir boş değer gözükmüyordu. Ancak veriyi dikkatli bir şekilde inceleyecek olursak, anlamladıramadığımız bir değer var gibi gözüküyor...

Endişeye gerek yok. Bu tarz sorunların önüne `.read_csv()` fonksiyonun parametrelerini kullanarak önüne geçmek oldukça kolay :)

In [5]:
df = pd.read_csv('https://bit.ly/2JRmGC2', 
                 na_values = -1,
                 index_col = 0
                )

In [6]:
df.head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.0,0.75,34.384843

`.read_csv()` fonksiyonunun kendi içerisinde elimizdeki veriyi doğru bir formatta okutabilmek için bir çok parametresi bulunur. Örnek olarak,

- Verilerinizin `sep` fonksiyonu ile nasıl ayrılacağını belirleyebilirsiniz (örneğin, virgüller için ',' veya sekmeler için '\t') 
- Verilerinizin yalnızca belirli bir kısmını `nrows` parametresi ile yükleyebilirsiniz.
- 2.000 gibi sayıları `thousands` parametresi ile tam sayılara dönüştürebilirsiniz.

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
type(df['calories'])

pandas.core.series.Series

In [9]:
type(df.calories)

pandas.core.series.Series

In [10]:
type(df.loc['100% Bran'])

pandas.core.series.Series

Kalori sütununa,
- Hem köşeli parantez `[]` kullanarak
- Hem de nokta yöntemiyle `.` de erişebileceğinizi unutmayın. 

Ancak bu durum, yalnızca sütun adı geçerli bir Python değişkeniyse geçerlidir (boşluk veya diğer özel karakterler içeren sütun adlarına yalnızca köşeli parantezler kullanılarak erişilebilir). Ayrıca veri çerçevesi satırlarına `.loc` ve satır indeksi ile erişebileceğimizi de unutmayın.

In [11]:
df.loc['100% Bran']

mfr                 N
type                C
calories           70
protein             4
fat                 1
sodium            130
fiber            10.0
carbo             5.0
sugars            6.0
potass          280.0
vitamins           25
shelf               3
weight            1.0
cups             0.33
rating      68.402973
Name: 100% Bran, dtype: object

## Veriyi Keşfetme

In [12]:
df.calories.describe()

count     77.000000
mean     106.883117
std       19.484119
min       50.000000
25%      100.000000
50%      110.000000
75%      110.000000
max      160.000000
Name: calories, dtype: float64

In [13]:
df.sugars.mean()

7.026315789473684

In [14]:
df.mfr.value_counts()

K    23
G    22
P     9
Q     8
R     8
N     6
A     1
Name: mfr, dtype: int64

`.value_counts()` fonksiyonunun sonucunda elde ettiğimiz değerlere ulaşmak için tekrardan `index` yapılarından yararlanabiliriz.

In [15]:
df.mfr.value_counts().loc['K']

23

## Veriyi Filtreleme

Zaman zaman verinin tümüyle çalışmak yerine, veri içerisinden belirli bir kısımla çalışma ihtiyacı duyarız. Bu sebeple, verilerimize çeşitli filtreleme ve maskeleme işlemleri uygularız.

In [16]:
mask = (df.calories > 100)

In [17]:
mask

name
100% Bran                    False
100% Natural Bran             True
All-Bran                     False
All-Bran with Extra Fiber    False
Almond Delight                True
                             ...
Triples                       True
Trix                          True
Wheat Chex                   False
Wheaties                     False
Wheaties Honey Gold           True
Name: calories, Length: 77, dtype: bool

Ancak filtreleme işlemi sonucunda elde ettiğimiz değerleri bir `DataFrame` içerisinde gösterirsek yalnızca `True` dönen satırları DataFrame'de tutmuş oluruz.

In [18]:
df[mask].head(10)

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.00,1.00,33.983679
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.00,0.75,34.384843
Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10.0,70.0,25,1,1.00,0.75,29.509541
Apple Jacks,K,C,110,2,0,125,1.0,11.0,14.0,30.0,25,2,1.00,1.00,33.174094
Basic 4,G,C,130,3,2,210,2.0,18.0,8.0,100.0,25,3,1.33,0.75,37.038562
Cap'n'Crunch,Q,C,120,1,2,220,0.0,12.0,12.0,35.0,25,2,1.00,0.75,18.042851
Cheerios,G,C,110,6,2,290,2.0,17.0,1.0,105.0,25,1,1.00,1.25,50.764999
Cinnamon Toast Crunch,G,C,120,1,3,210,0.0,13.0,9.0,45.0,25,2,1.00,0.75,19.823573
Clusters,G,C,110,3,2,140,2.0,13.0,7.0,105.0,25,3,1.00,0.50,40.400208
Cocoa Puffs,G,C,110,1,1,180,0.0,12.0,13.0,55.0,25,2,1.00,1.00,22.736446

Tabi ki bir değişken tanımlaması yapmadan da bu tarz işlemleri yapmak mümkün :)

In [19]:
df[df.calories > 100].head(10)

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.00,1.00,33.983679
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.00,0.75,34.384843
Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10.0,70.0,25,1,1.00,0.75,29.509541
Apple Jacks,K,C,110,2,0,125,1.0,11.0,14.0,30.0,25,2,1.00,1.00,33.174094
Basic 4,G,C,130,3,2,210,2.0,18.0,8.0,100.0,25,3,1.33,0.75,37.038562
Cap'n'Crunch,Q,C,120,1,2,220,0.0,12.0,12.0,35.0,25,2,1.00,0.75,18.042851
Cheerios,G,C,110,6,2,290,2.0,17.0,1.0,105.0,25,1,1.00,1.25,50.764999
Cinnamon Toast Crunch,G,C,120,1,3,210,0.0,13.0,9.0,45.0,25,2,1.00,0.75,19.823573
Clusters,G,C,110,3,2,140,2.0,13.0,7.0,105.0,25,3,1.00,0.50,40.400208
Cocoa Puffs,G,C,110,1,1,180,0.0,12.0,13.0,55.0,25,2,1.00,1.00,22.736446

Verimiz üzerinde, birden fazla filtre uygulamak istersek de, `and (&)`, `or (|)` operatörlerini kullanmak istediğimiz sonuca kolayca ulaşmamıza sağlayacaktır.

In [20]:
mask = (df.calories > 100) & (df.sugars < 8) & ((df.mfr == 'K') | (df.mfr == 'G'))

In [21]:
df[mask]

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
Cheerios,G,C,110,6,2,290,2.0,17.0,1.0,105.0,25,1,1.00,1.25,50.764999
Clusters,G,C,110,3,2,140,2.0,13.0,7.0,105.0,25,3,1.00,0.50,40.400208
Cracklin' Oat Bran,K,C,110,3,3,140,4.0,10.0,7.0,160.0,25,3,1.00,0.50,40.448772
Crispix,K,C,110,2,0,220,1.0,21.0,3.0,30.0,25,3,1.00,1.00,46.895644
Just Right Crunchy Nuggets,K,C,110,2,1,170,1.0,17.0,6.0,60.0,100,3,1.00,1.00,36.523683
Kix,G,C,110,2,1,260,0.0,21.0,3.0,40.0,25,2,1.00,1.50,39.241114
Nutri-Grain Almond-Raisin,K,C,140,3,2,220,3.0,21.0,7.0,130.0,25,3,1.33,0.67,40.692320
Rice Krispies,K,C,110,2,0,290,0.0,22.0,3.0,35.0,25,1,1.00,1.00,40.560159
Special K,K,C,110,6,0,230,1.0,16.0,3.0,55.0,25,1,1.00,1.00,53.131324
Total Corn Flakes,G,C,110,2,1,200,0.0,21.0,3.0,35.0,100,3,1.00,1.00,38.839746
Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.0,25,3,1.00,0.75,39.106174

## Boş Değerler

In [22]:
df.isna().sum()

mfr         0
type        0
calories    0
protein     0
fat         0
sodium      0
fiber       0
carbo       1
sugars      1
potass      2
vitamins    0
shelf       0
weight      0
cups        0
rating      0
dtype: int64

Yukarıda gördüğümüz gibi veri setimizin tümünde toplam 4 eksik değerimiz bulunmakta, peki bunları ne yapmak lazım?

Bu durumu çözüme kavuşturmak için şu anki bilgilerimizden yola çıkarak uygulayabileceğimiz 2 yöntem bulunmakta,
- Boş değer barındıran satırları silme
- Boş değerleri `mean` veya `median` gibi istatiksel değerlerden yararlanarak doldurma

In [23]:
df.shape

(77, 15)

In [24]:
df.dropna(subset=['carbo','sugars']).head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.0,0.75,34.384843

In [25]:
df.dropna(subset=['carbo','sugars']).shape

(76, 15)

In [26]:
df.shape

(77, 15)

> **HATIRLATMA:** Eğer yaptığınız bu değişikliğin orijinal veri setiniz için de uygulanmasını istiyorsanız `inplace=True` parametresini eklemeyi unutmayın :)

In [27]:
df.dropna(subset=['carbo', 'sugars'], inplace=True)

In [28]:
df.shape

(76, 15)

Hadi `potass` sütunundaki boş değerleri de `median` değerleriyle dolduralım.

In [29]:
potass_median = df.potass.median()

potass_median

90.0

In [30]:
df.potass.fillna(potass_median, inplace=True)

In [31]:
df.head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,90.0,25,3,1.0,0.75,34.384843

## Veriye Fonksiyonlar Uygulama

In [32]:
df.vitamins.value_counts()

25     63
0       7
100     6
Name: vitamins, dtype: int64

`value_counts()` fonksiyonundan elde ettiğimiz sonuca göre `vitamins` sütunumuz sadece 3 farklı sayısal değer barındırmakta. Bu senepten dolayı, hadi `vitamin_at_least_25` adında yeni bir sütun oluşturalım.

In [33]:
df['vitamin_at_least_25'] = df.vitamins >= 25

In [34]:
df.head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,vitamin_at_least_25
name,,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973,True
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679,False
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505,True
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912,True
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,90.0,25,3,1.0,0.75,34.384843,True

### Apply()

Peki, veri setimiz içerisindeki ürünlerin vitamin değerlerine göre onları gruplamak istesem? Bunu, `.apply()` fonksiyonunu kullanarak rahatlıkla yapabilirim.

In [35]:
def get_vitamin_level(vitamins):
    if vitamins > 99:
        return 'high'
    elif vitamins > 24:
        return 'medium'
    else:
        return 'low'

In [36]:
get_vitamin_level(100)

'high'

In [37]:
get_vitamin_level(25)

'medium'

In [38]:
df.vitamins.apply(get_vitamin_level)

name
100% Bran                    medium
100% Natural Bran               low
All-Bran                     medium
All-Bran with Extra Fiber    medium
Almond Delight               medium
                              ...
Triples                      medium
Trix                         medium
Wheat Chex                   medium
Wheaties                     medium
Wheaties Honey Gold          medium
Name: vitamins, Length: 76, dtype: object

In [39]:
df['vitamin_level'] = df.vitamins.apply(get_vitamin_level)

In [40]:
df.head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,vitamin_at_least_25,vitamin_level
name,,,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973,True,medium
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679,False,low
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505,True,medium
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912,True,medium
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,90.0,25,3,1.0,0.75,34.384843,True,medium

Buna benzer işlemleri `def` le fonksiyon tanımlamadan `lambda` fonksiyonunda yararlanarak da yapabilirdik :)

In [41]:
df['vitamin_perc'] = df.vitamins.apply(lambda x: str(x)+'%')

In [42]:
df.head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,vitamin_at_least_25,vitamin_level,vitamin_perc
name,,,,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973,True,medium,25%
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679,False,low,0%
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505,True,medium,25%
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912,True,medium,25%
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,90.0,25,3,1.0,0.75,34.384843,True,medium,25%

### Map()

`.apply()` bizim için çok kullanışlı ve sevdiğimiz bir fonksiyon, aynı `.map()` fonksiyonu gibi :)

In [43]:
mfr_dict = {
    'A': 'Am Home Food Prods',
    'G': 'General Mills',
    'K': 'Kelloggs',
    'N': 'Nabisco',
    'P': 'Post',
    'Q': 'Quaker Oats',
    'R': 'Ralston Purina'
}

Tek yapmamız gereken tanımladığımız `dictionary` yapısını elimizdeki `DataFrame` ile birleştirmek :)

In [44]:
df.mfr.map(mfr_dict)

name
100% Bran                           Nabisco
100% Natural Bran               Quaker Oats
All-Bran                           Kelloggs
All-Bran with Extra Fiber          Kelloggs
Almond Delight               Ralston Purina
                                  ...
Triples                       General Mills
Trix                          General Mills
Wheat Chex                   Ralston Purina
Wheaties                      General Mills
Wheaties Honey Gold           General Mills
Name: mfr, Length: 76, dtype: object

In [45]:
df['manufacturer'] = df.mfr.map(mfr_dict)

In [46]:
df.head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,vitamin_at_least_25,vitamin_level,vitamin_perc,manufacturer
name,,,,,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973,True,medium,25%,Nabisco
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679,False,low,0%,Quaker Oats
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505,True,medium,25%,Kelloggs
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912,True,medium,25%,Kelloggs
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,90.0,25,3,1.0,0.75,34.384843,True,medium,25%,Ralston Purina