In [1]:
import psycopg2
import pandas as pd

In [2]:
params = {
    "host": "localhost",
    "user": "postgres",
    "port": 5432,
    "password": "şifre" 
}
connection = psycopg2.connect(**params, dbname= "DS_Bootcamp")

In [3]:
pd.read_sql("select * from introduction.name_freq", connection)

        state gender  year      name  freq
0          AK      F  1951     Linda    79
1          AK      F  1951      Mary    77
2          AK      F  1951  Patricia    45
3          AK      F  1951     Susan    45
4          AK      F  1951   Barbara    35
...       ...    ...   ...       ...   ...
4382229    WY      M  2016  Santiago     5
4382230    WY      M  2016     Titus     5
4382231    WY      M  2016    Tobias     5
4382232    WY      M  2016    Trevor     5
4382233    WY      M  2016        Ty     5

[4382234 rows x 5 columns]

In [4]:
pd.read_sql("select * from introduction.region", connection)

   state        region
0     AL         South
1     AK       Pacific
2     AZ      Mountain
3     AR         South
4     CA       Pacific
5     CO      Mountain
6     CT   New_England
7     DC  Mid_Atlantic
8     DE         South
9     FL         South
10    GA         South
11    HI       Pacific
12    ID      Mountain
13    IL       Midwest
14    IN       Midwest
15    IA       Midwest
16    KS       Midwest
17    KY         South
18    LA         South
19    ME   New_England
20    MD         South
21    MA   New_England
22    MN       Midwest
23    MS         South
24    MO       Midwest
25    MT      Mountain
26    NE       Midwest
27    NV      Mountain
28    NJ  Mid_Atlantic
29    NM      Mountain
30    NY  Mid_Atlantic
31    NC         South
32    ND       Midwest
33    OH       Midwest
34    OK         South
35    OR       Pacific
36    PA  Mid_Atlantic
37    RI   New_England
38    SC         South
39    SD       Midwest
40    TN         South
41    TX         South
42    UT      Mountain
43    VT   New_England
44    VA         South
45    WA       Pacific
46    WV         South
47    WI       Midwest
48    WY      Mountain
49    NH   New_England

In [5]:
pd.read_sql("""select * from introduction.name_freq n 
            join introduction.region r on n.state = r.state 
            where year=1951""", connection)

      state gender  year      name  freq state    region
0        AK      F  1951     Linda    79    AK   Pacific
1        AK      F  1951      Mary    77    AK   Pacific
2        AK      F  1951  Patricia    45    AK   Pacific
3        AK      F  1951     Susan    45    AK   Pacific
4        AK      F  1951   Barbara    35    AK   Pacific
...     ...    ...   ...       ...   ...   ...       ...
43435    WY      M  1951     Monte     5    WY  Mountain
43436    WY      M  1951      Rudy     5    WY  Mountain
43437    WY      M  1951  Terrance     5    WY  Mountain
43438    WY      M  1951     Vance     5    WY  Mountain
43439    WY      M  1951    Virgil     5    WY  Mountain

[43440 rows x 7 columns]

In [6]:
dataFrame = pd.read_sql("""select * from introduction.name_freq n 
            join introduction.region r on n.state = r.state""", connection)

In [7]:
dataFrame

        state gender  year      name  freq state    region
0          AK      F  1951     Linda    79    AK   Pacific
1          AK      F  1951      Mary    77    AK   Pacific
2          AK      F  1951  Patricia    45    AK   Pacific
3          AK      F  1951     Susan    45    AK   Pacific
4          AK      F  1951   Barbara    35    AK   Pacific
...       ...    ...   ...       ...   ...   ...       ...
4246937    WY      M  2016  Santiago     5    WY  Mountain
4246938    WY      M  2016     Titus     5    WY  Mountain
4246939    WY      M  2016    Tobias     5    WY  Mountain
4246940    WY      M  2016    Trevor     5    WY  Mountain
4246941    WY      M  2016        Ty     5    WY  Mountain

[4246942 rows x 7 columns]

In [8]:
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4246942 entries, 0 to 4246941
Data columns (total 7 columns):
 #   Column  Dtype
---  ------  -----
 0   state   object
 1   gender  object
 2   year    int64
 3   name    object
 4   freq    int64
 5   state   object
 6   region  object
dtypes: int64(2), object(5)
memory usage: 226.8+ MB

In [9]:
connection.close()